# Generated by Django 2.2 on 2023-01-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('birthdate', models.DateField()),
                ('linkedin', models.URLField()),
                ('phone_number', models.CharField(max_length=20)),
                ('city', models.TextField()),
                ('Degree', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('summary', models.TextField(null='True')),
                ('image', models.ImageField(upload_to='projects/')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('summary', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('map_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='designer_responsibilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility1', models.TextField(blank='True', max_length=200)),
                ('responsibility2', models.TextField(blank='True', max_length=200)),
                ('responsibility3', models.TextField(blank='True', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=50)),
                ('clients_no', models.CharField(max_length=50)),
                ('project_no', models.CharField(max_length=50)),
                ('support_hour', models.CharField(max_length=50)),
                ('staff_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='projects/')),
                ('link', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resumes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('summary', models.TextField(null='True')),
                ('individual_summary', models.TextField(null='True')),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('experience_in', models.TextField()),
                ('education', models.TextField()),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('college_name', models.CharField(max_length=255)),
                ('collge_summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200)),
                ('service_name', models.CharField(max_length=100)),
                ('icon_name', models.CharField(max_length=20, null=True)),
                ('service_summary', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('summary', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=30)),
                ('rating', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200)),
                ('Full_name', models.CharField(max_length=50, null=True)),
                ('profession', models.CharField(max_length=30)),
                ('Testimony_Photo', models.ImageField(null=True, upload_to='projects/')),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='webresponsibilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility1', models.TextField(blank='True', max_length=200)),
                ('responsibility2', models.TextField(blank='True', max_length=200)),
                ('responsibility3', models.TextField(blank='True', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='workhistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=50)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.CharField(max_length=50)),
                ('responsibilities', models.TextField(blank='True', max_length=200)),
            ],
        ),
    ]
